package com.my.test.springmvc.dao.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ProductExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table product
     *
     * @mbg.generated Mon May 08 15:38:54 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table product
     *
     * @mbg.generated Mon May 08 15:38:54 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table product
     *
     * @mbg.generated Mon May 08 15:38:54 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated Mon May 08 15:38:54 CST 2017
     */
    public ProductExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated Mon May 08 15:38:54 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated Mon May 08 15:38:54 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated Mon May 08 15:38:54 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated Mon May 08 15:38:54 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated Mon May 08 15:38:54 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated Mon May 08 15:38:54 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated Mon May 08 15:38:54 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated Mon May 08 15:38:54 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated Mon May 08 15:38:54 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated Mon May 08 15:38:54 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table product
     *
     * @mbg.generated Mon May 08 15:38:54 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andProductNoIsNull() {
            addCriterion("Product_NO is null");
            return (Criteria) this;
        }

        public Criteria andProductNoIsNotNull() {
            addCriterion("Product_NO is not null");
            return (Criteria) this;
        }

        public Criteria andProductNoEqualTo(String value) {
            addCriterion("Product_NO =", value, "productNo");
            return (Criteria) this;
        }

        public Criteria andProductNoNotEqualTo(String value) {
            addCriterion("Product_NO <>", value, "productNo");
            return (Criteria) this;
        }

        public Criteria andProductNoGreaterThan(String value) {
            addCriterion("Product_NO >", value, "productNo");
            return (Criteria) this;
        }

        public Criteria andProductNoGreaterThanOrEqualTo(String value) {
            addCriterion("Product_NO >=", value, "productNo");
            return (Criteria) this;
        }

        public Criteria andProductNoLessThan(String value) {
            addCriterion("Product_NO <", value, "productNo");
            return (Criteria) this;
        }

        public Criteria andProductNoLessThanOrEqualTo(String value) {
            addCriterion("Product_NO <=", value, "productNo");
            return (Criteria) this;
        }

        public Criteria andProductNoLike(String value) {
            addCriterion("Product_NO like", value, "productNo");
            return (Criteria) this;
        }

        public Criteria andProductNoNotLike(String value) {
            addCriterion("Product_NO not like", value, "productNo");
            return (Criteria) this;
        }

        public Criteria andProductNoIn(List<String> values) {
            addCriterion("Product_NO in", values, "productNo");
            return (Criteria) this;
        }

        public Criteria andProductNoNotIn(List<String> values) {
            addCriterion("Product_NO not in", values, "productNo");
            return (Criteria) this;
        }

        public Criteria andProductNoBetween(String value1, String value2) {
            addCriterion("Product_NO between", value1, value2, "productNo");
            return (Criteria) this;
        }

        public Criteria andProductNoNotBetween(String value1, String value2) {
            addCriterion("Product_NO not between", value1, value2, "productNo");
            return (Criteria) this;
        }

        public Criteria andProductNameIsNull() {
            addCriterion("Product_Name is null");
            return (Criteria) this;
        }

        public Criteria andProductNameIsNotNull() {
            addCriterion("Product_Name is not null");
            return (Criteria) this;
        }

        public Criteria andProductNameEqualTo(String value) {
            addCriterion("Product_Name =", value, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameNotEqualTo(String value) {
            addCriterion("Product_Name <>", value, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameGreaterThan(String value) {
            addCriterion("Product_Name >", value, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameGreaterThanOrEqualTo(String value) {
            addCriterion("Product_Name >=", value, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameLessThan(String value) {
            addCriterion("Product_Name <", value, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameLessThanOrEqualTo(String value) {
            addCriterion("Product_Name <=", value, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameLike(String value) {
            addCriterion("Product_Name like", value, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameNotLike(String value) {
            addCriterion("Product_Name not like", value, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameIn(List<String> values) {
            addCriterion("Product_Name in", values, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameNotIn(List<String> values) {
            addCriterion("Product_Name not in", values, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameBetween(String value1, String value2) {
            addCriterion("Product_Name between", value1, value2, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameNotBetween(String value1, String value2) {
            addCriterion("Product_Name not between", value1, value2, "productName");
            return (Criteria) this;
        }

        public Criteria andProductBranchIsNull() {
            addCriterion("Product_Branch is null");
            return (Criteria) this;
        }

        public Criteria andProductBranchIsNotNull() {
            addCriterion("Product_Branch is not null");
            return (Criteria) this;
        }

        public Criteria andProductBranchEqualTo(String value) {
            addCriterion("Product_Branch =", value, "productBranch");
            return (Criteria) this;
        }

        public Criteria andProductBranchNotEqualTo(String value) {
            addCriterion("Product_Branch <>", value, "productBranch");
            return (Criteria) this;
        }

        public Criteria andProductBranchGreaterThan(String value) {
            addCriterion("Product_Branch >", value, "productBranch");
            return (Criteria) this;
        }

        public Criteria andProductBranchGreaterThanOrEqualTo(String value) {
            addCriterion("Product_Branch >=", value, "productBranch");
            return (Criteria) this;
        }

        public Criteria andProductBranchLessThan(String value) {
            addCriterion("Product_Branch <", value, "productBranch");
            return (Criteria) this;
        }

        public Criteria andProductBranchLessThanOrEqualTo(String value) {
            addCriterion("Product_Branch <=", value, "productBranch");
            return (Criteria) this;
        }

        public Criteria andProductBranchLike(String value) {
            addCriterion("Product_Branch like", value, "productBranch");
            return (Criteria) this;
        }

        public Criteria andProductBranchNotLike(String value) {
            addCriterion("Product_Branch not like", value, "productBranch");
            return (Criteria) this;
        }

        public Criteria andProductBranchIn(List<String> values) {
            addCriterion("Product_Branch in", values, "productBranch");
            return (Criteria) this;
        }

        public Criteria andProductBranchNotIn(List<String> values) {
            addCriterion("Product_Branch not in", values, "productBranch");
            return (Criteria) this;
        }

        public Criteria andProductBranchBetween(String value1, String value2) {
            addCriterion("Product_Branch between", value1, value2, "productBranch");
            return (Criteria) this;
        }

        public Criteria andProductBranchNotBetween(String value1, String value2) {
            addCriterion("Product_Branch not between", value1, value2, "productBranch");
            return (Criteria) this;
        }

        public Criteria andProductStatusIsNull() {
            addCriterion("Product_Status is null");
            return (Criteria) this;
        }

        public Criteria andProductStatusIsNotNull() {
            addCriterion("Product_Status is not null");
            return (Criteria) this;
        }

        public Criteria andProductStatusEqualTo(String value) {
            addCriterion("Product_Status =", value, "productStatus");
            return (Criteria) this;
        }

        public Criteria andProductStatusNotEqualTo(String value) {
            addCriterion("Product_Status <>", value, "productStatus");
            return (Criteria) this;
        }

        public Criteria andProductStatusGreaterThan(String value) {
            addCriterion("Product_Status >", value, "productStatus");
            return (Criteria) this;
        }

        public Criteria andProductStatusGreaterThanOrEqualTo(String value) {
            addCriterion("Product_Status >=", value, "productStatus");
            return (Criteria) this;
        }

        public Criteria andProductStatusLessThan(String value) {
            addCriterion("Product_Status <", value, "productStatus");
            return (Criteria) this;
        }

        public Criteria andProductStatusLessThanOrEqualTo(String value) {
            addCriterion("Product_Status <=", value, "productStatus");
            return (Criteria) this;
        }

        public Criteria andProductStatusLike(String value) {
            addCriterion("Product_Status like", value, "productStatus");
            return (Criteria) this;
        }

        public Criteria andProductStatusNotLike(String value) {
            addCriterion("Product_Status not like", value, "productStatus");
            return (Criteria) this;
        }

        public Criteria andProductStatusIn(List<String> values) {
            addCriterion("Product_Status in", values, "productStatus");
            return (Criteria) this;
        }

        public Criteria andProductStatusNotIn(List<String> values) {
            addCriterion("Product_Status not in", values, "productStatus");
            return (Criteria) this;
        }

        public Criteria andProductStatusBetween(String value1, String value2) {
            addCriterion("Product_Status between", value1, value2, "productStatus");
            return (Criteria) this;
        }

        public Criteria andProductStatusNotBetween(String value1, String value2) {
            addCriterion("Product_Status not between", value1, value2, "productStatus");
            return (Criteria) this;
        }

        public Criteria andProductCatenoIsNull() {
            addCriterion("Product_CateNO is null");
            return (Criteria) this;
        }

        public Criteria andProductCatenoIsNotNull() {
            addCriterion("Product_CateNO is not null");
            return (Criteria) this;
        }

        public Criteria andProductCatenoEqualTo(String value) {
            addCriterion("Product_CateNO =", value, "productCateno");
            return (Criteria) this;
        }

        public Criteria andProductCatenoNotEqualTo(String value) {
            addCriterion("Product_CateNO <>", value, "productCateno");
            return (Criteria) this;
        }

        public Criteria andProductCatenoGreaterThan(String value) {
            addCriterion("Product_CateNO >", value, "productCateno");
            return (Criteria) this;
        }

        public Criteria andProductCatenoGreaterThanOrEqualTo(String value) {
            addCriterion("Product_CateNO >=", value, "productCateno");
            return (Criteria) this;
        }

        public Criteria andProductCatenoLessThan(String value) {
            addCriterion("Product_CateNO <", value, "productCateno");
            return (Criteria) this;
        }

        public Criteria andProductCatenoLessThanOrEqualTo(String value) {
            addCriterion("Product_CateNO <=", value, "productCateno");
            return (Criteria) this;
        }

        public Criteria andProductCatenoLike(String value) {
            addCriterion("Product_CateNO like", value, "productCateno");
            return (Criteria) this;
        }

        public Criteria andProductCatenoNotLike(String value) {
            addCriterion("Product_CateNO not like", value, "productCateno");
            return (Criteria) this;
        }

        public Criteria andProductCatenoIn(List<String> values) {
            addCriterion("Product_CateNO in", values, "productCateno");
            return (Criteria) this;
        }

        public Criteria andProductCatenoNotIn(List<String> values) {
            addCriterion("Product_CateNO not in", values, "productCateno");
            return (Criteria) this;
        }

        public Criteria andProductCatenoBetween(String value1, String value2) {
            addCriterion("Product_CateNO between", value1, value2, "productCateno");
            return (Criteria) this;
        }

        public Criteria andProductCatenoNotBetween(String value1, String value2) {
            addCriterion("Product_CateNO not between", value1, value2, "productCateno");
            return (Criteria) this;
        }

        public Criteria andProductPriceIsNull() {
            addCriterion("Product_Price is null");
            return (Criteria) this;
        }

        public Criteria andProductPriceIsNotNull() {
            addCriterion("Product_Price is not null");
            return (Criteria) this;
        }

        public Criteria andProductPriceEqualTo(BigDecimal value) {
            addCriterion("Product_Price =", value, "productPrice");
            return (Criteria) this;
        }

        public Criteria andProductPriceNotEqualTo(BigDecimal value) {
            addCriterion("Product_Price <>", value, "productPrice");
            return (Criteria) this;
        }

        public Criteria andProductPriceGreaterThan(BigDecimal value) {
            addCriterion("Product_Price >", value, "productPrice");
            return (Criteria) this;
        }

        public Criteria andProductPriceGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("Product_Price >=", value, "productPrice");
            return (Criteria) this;
        }

        public Criteria andProductPriceLessThan(BigDecimal value) {
            addCriterion("Product_Price <", value, "productPrice");
            return (Criteria) this;
        }

        public Criteria andProductPriceLessThanOrEqualTo(BigDecimal value) {
            addCriterion("Product_Price <=", value, "productPrice");
            return (Criteria) this;
        }

        public Criteria andProductPriceIn(List<BigDecimal> values) {
            addCriterion("Product_Price in", values, "productPrice");
            return (Criteria) this;
        }

        public Criteria andProductPriceNotIn(List<BigDecimal> values) {
            addCriterion("Product_Price not in", values, "productPrice");
            return (Criteria) this;
        }

        public Criteria andProductPriceBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("Product_Price between", value1, value2, "productPrice");
            return (Criteria) this;
        }

        public Criteria andProductPriceNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("Product_Price not between", value1, value2, "productPrice");
            return (Criteria) this;
        }

        public Criteria andProductPvIsNull() {
            addCriterion("Product_PV is null");
            return (Criteria) this;
        }

        public Criteria andProductPvIsNotNull() {
            addCriterion("Product_PV is not null");
            return (Criteria) this;
        }

        public Criteria andProductPvEqualTo(BigDecimal value) {
            addCriterion("Product_PV =", value, "productPv");
            return (Criteria) this;
        }

        public Criteria andProductPvNotEqualTo(BigDecimal value) {
            addCriterion("Product_PV <>", value, "productPv");
            return (Criteria) this;
        }

        public Criteria andProductPvGreaterThan(BigDecimal value) {
            addCriterion("Product_PV >", value, "productPv");
            return (Criteria) this;
        }

        public Criteria andProductPvGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("Product_PV >=", value, "productPv");
            return (Criteria) this;
        }

        public Criteria andProductPvLessThan(BigDecimal value) {
            addCriterion("Product_PV <", value, "productPv");
            return (Criteria) this;
        }

        public Criteria andProductPvLessThanOrEqualTo(BigDecimal value) {
            addCriterion("Product_PV <=", value, "productPv");
            return (Criteria) this;
        }

        public Criteria andProductPvIn(List<BigDecimal> values) {
            addCriterion("Product_PV in", values, "productPv");
            return (Criteria) this;
        }

        public Criteria andProductPvNotIn(List<BigDecimal> values) {
            addCriterion("Product_PV not in", values, "productPv");
            return (Criteria) this;
        }

        public Criteria andProductPvBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("Product_PV between", value1, value2, "productPv");
            return (Criteria) this;
        }

        public Criteria andProductPvNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("Product_PV not between", value1, value2, "productPv");
            return (Criteria) this;
        }

        public Criteria andProductNvrunitIsNull() {
            addCriterion("Product_nvrUnit is null");
            return (Criteria) this;
        }

        public Criteria andProductNvrunitIsNotNull() {
            addCriterion("Product_nvrUnit is not null");
            return (Criteria) this;
        }

        public Criteria andProductNvrunitEqualTo(String value) {
            addCriterion("Product_nvrUnit =", value, "productNvrunit");
            return (Criteria) this;
        }

        public Criteria andProductNvrunitNotEqualTo(String value) {
            addCriterion("Product_nvrUnit <>", value, "productNvrunit");
            return (Criteria) this;
        }

        public Criteria andProductNvrunitGreaterThan(String value) {
            addCriterion("Product_nvrUnit >", value, "productNvrunit");
            return (Criteria) this;
        }

        public Criteria andProductNvrunitGreaterThanOrEqualTo(String value) {
            addCriterion("Product_nvrUnit >=", value, "productNvrunit");
            return (Criteria) this;
        }

        public Criteria andProductNvrunitLessThan(String value) {
            addCriterion("Product_nvrUnit <", value, "productNvrunit");
            return (Criteria) this;
        }

        public Criteria andProductNvrunitLessThanOrEqualTo(String value) {
            addCriterion("Product_nvrUnit <=", value, "productNvrunit");
            return (Criteria) this;
        }

        public Criteria andProductNvrunitLike(String value) {
            addCriterion("Product_nvrUnit like", value, "productNvrunit");
            return (Criteria) this;
        }

        public Criteria andProductNvrunitNotLike(String value) {
            addCriterion("Product_nvrUnit not like", value, "productNvrunit");
            return (Criteria) this;
        }

        public Criteria andProductNvrunitIn(List<String> values) {
            addCriterion("Product_nvrUnit in", values, "productNvrunit");
            return (Criteria) this;
        }

        public Criteria andProductNvrunitNotIn(List<String> values) {
            addCriterion("Product_nvrUnit not in", values, "productNvrunit");
            return (Criteria) this;
        }

        public Criteria andProductNvrunitBetween(String value1, String value2) {
            addCriterion("Product_nvrUnit between", value1, value2, "productNvrunit");
            return (Criteria) this;
        }

        public Criteria andProductNvrunitNotBetween(String value1, String value2) {
            addCriterion("Product_nvrUnit not between", value1, value2, "productNvrunit");
            return (Criteria) this;
        }

        public Criteria andProductFormatIsNull() {
            addCriterion("Product_Format is null");
            return (Criteria) this;
        }

        public Criteria andProductFormatIsNotNull() {
            addCriterion("Product_Format is not null");
            return (Criteria) this;
        }

        public Criteria andProductFormatEqualTo(String value) {
            addCriterion("Product_Format =", value, "productFormat");
            return (Criteria) this;
        }

        public Criteria andProductFormatNotEqualTo(String value) {
            addCriterion("Product_Format <>", value, "productFormat");
            return (Criteria) this;
        }

        public Criteria andProductFormatGreaterThan(String value) {
            addCriterion("Product_Format >", value, "productFormat");
            return (Criteria) this;
        }

        public Criteria andProductFormatGreaterThanOrEqualTo(String value) {
            addCriterion("Product_Format >=", value, "productFormat");
            return (Criteria) this;
        }

        public Criteria andProductFormatLessThan(String value) {
            addCriterion("Product_Format <", value, "productFormat");
            return (Criteria) this;
        }

        public Criteria andProductFormatLessThanOrEqualTo(String value) {
            addCriterion("Product_Format <=", value, "productFormat");
            return (Criteria) this;
        }

        public Criteria andProductFormatLike(String value) {
            addCriterion("Product_Format like", value, "productFormat");
            return (Criteria) this;
        }

        public Criteria andProductFormatNotLike(String value) {
            addCriterion("Product_Format not like", value, "productFormat");
            return (Criteria) this;
        }

        public Criteria andProductFormatIn(List<String> values) {
            addCriterion("Product_Format in", values, "productFormat");
            return (Criteria) this;
        }

        public Criteria andProductFormatNotIn(List<String> values) {
            addCriterion("Product_Format not in", values, "productFormat");
            return (Criteria) this;
        }

        public Criteria andProductFormatBetween(String value1, String value2) {
            addCriterion("Product_Format between", value1, value2, "productFormat");
            return (Criteria) this;
        }

        public Criteria andProductFormatNotBetween(String value1, String value2) {
            addCriterion("Product_Format not between", value1, value2, "productFormat");
            return (Criteria) this;
        }

        public Criteria andProductAddtimeIsNull() {
            addCriterion("Product_AddTime is null");
            return (Criteria) this;
        }

        public Criteria andProductAddtimeIsNotNull() {
            addCriterion("Product_AddTime is not null");
            return (Criteria) this;
        }

        public Criteria andProductAddtimeEqualTo(Date value) {
            addCriterion("Product_AddTime =", value, "productAddtime");
            return (Criteria) this;
        }

        public Criteria andProductAddtimeNotEqualTo(Date value) {
            addCriterion("Product_AddTime <>", value, "productAddtime");
            return (Criteria) this;
        }

        public Criteria andProductAddtimeGreaterThan(Date value) {
            addCriterion("Product_AddTime >", value, "productAddtime");
            return (Criteria) this;
        }

        public Criteria andProductAddtimeGreaterThanOrEqualTo(Date value) {
            addCriterion("Product_AddTime >=", value, "productAddtime");
            return (Criteria) this;
        }

        public Criteria andProductAddtimeLessThan(Date value) {
            addCriterion("Product_AddTime <", value, "productAddtime");
            return (Criteria) this;
        }

        public Criteria andProductAddtimeLessThanOrEqualTo(Date value) {
            addCriterion("Product_AddTime <=", value, "productAddtime");
            return (Criteria) this;
        }

        public Criteria andProductAddtimeIn(List<Date> values) {
            addCriterion("Product_AddTime in", values, "productAddtime");
            return (Criteria) this;
        }

        public Criteria andProductAddtimeNotIn(List<Date> values) {
            addCriterion("Product_AddTime not in", values, "productAddtime");
            return (Criteria) this;
        }

        public Criteria andProductAddtimeBetween(Date value1, Date value2) {
            addCriterion("Product_AddTime between", value1, value2, "productAddtime");
            return (Criteria) this;
        }

        public Criteria andProductAddtimeNotBetween(Date value1, Date value2) {
            addCriterion("Product_AddTime not between", value1, value2, "productAddtime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table product
     *
     * @mbg.generated do_not_delete_during_merge Mon May 08 15:38:54 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table product
     *
     * @mbg.generated Mon May 08 15:38:54 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}