package com.my.test.springmvc.dao.model;

import java.math.BigDecimal;
import java.util.Date;

public class Product {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.Product_NO
     *
     * @mbg.generated Mon May 08 15:38:54 CST 2017
     */
    private String productNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.Product_Name
     *
     * @mbg.generated Mon May 08 15:38:54 CST 2017
     */
    private String productName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.Product_Branch
     *
     * @mbg.generated Mon May 08 15:38:54 CST 2017
     */
    private String productBranch;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.Product_Status
     *
     * @mbg.generated Mon May 08 15:38:54 CST 2017
     */
    private String productStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.Product_CateNO
     *
     * @mbg.generated Mon May 08 15:38:54 CST 2017
     */
    private String productCateno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.Product_Price
     *
     * @mbg.generated Mon May 08 15:38:54 CST 2017
     */
    private BigDecimal productPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.Product_PV
     *
     * @mbg.generated Mon May 08 15:38:54 CST 2017
     */
    private BigDecimal productPv;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.Product_nvrUnit
     *
     * @mbg.generated Mon May 08 15:38:54 CST 2017
     */
    private String productNvrunit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.Product_Format
     *
     * @mbg.generated Mon May 08 15:38:54 CST 2017
     */
    private String productFormat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.Product_AddTime
     *
     * @mbg.generated Mon May 08 15:38:54 CST 2017
     */
    private Date productAddtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.Product_NO
     *
     * @return the value of product.Product_NO
     *
     * @mbg.generated Mon May 08 15:38:54 CST 2017
     */
    public String getProductNo() {
        return productNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.Product_NO
     *
     * @param productNo the value for product.Product_NO
     *
     * @mbg.generated Mon May 08 15:38:54 CST 2017
     */
    public void setProductNo(String productNo) {
        this.productNo = productNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.Product_Name
     *
     * @return the value of product.Product_Name
     *
     * @mbg.generated Mon May 08 15:38:54 CST 2017
     */
    public String getProductName() {
        return productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.Product_Name
     *
     * @param productName the value for product.Product_Name
     *
     * @mbg.generated Mon May 08 15:38:54 CST 2017
     */
    public void setProductName(String productName) {
        this.productName = productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.Product_Branch
     *
     * @return the value of product.Product_Branch
     *
     * @mbg.generated Mon May 08 15:38:54 CST 2017
     */
    public String getProductBranch() {
        return productBranch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.Product_Branch
     *
     * @param productBranch the value for product.Product_Branch
     *
     * @mbg.generated Mon May 08 15:38:54 CST 2017
     */
    public void setProductBranch(String productBranch) {
        this.productBranch = productBranch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.Product_Status
     *
     * @return the value of product.Product_Status
     *
     * @mbg.generated Mon May 08 15:38:54 CST 2017
     */
    public String getProductStatus() {
        return productStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.Product_Status
     *
     * @param productStatus the value for product.Product_Status
     *
     * @mbg.generated Mon May 08 15:38:54 CST 2017
     */
    public void setProductStatus(String productStatus) {
        this.productStatus = productStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.Product_CateNO
     *
     * @return the value of product.Product_CateNO
     *
     * @mbg.generated Mon May 08 15:38:54 CST 2017
     */
    public String getProductCateno() {
        return productCateno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.Product_CateNO
     *
     * @param productCateno the value for product.Product_CateNO
     *
     * @mbg.generated Mon May 08 15:38:54 CST 2017
     */
    public void setProductCateno(String productCateno) {
        this.productCateno = productCateno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.Product_Price
     *
     * @return the value of product.Product_Price
     *
     * @mbg.generated Mon May 08 15:38:54 CST 2017
     */
    public BigDecimal getProductPrice() {
        return productPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.Product_Price
     *
     * @param productPrice the value for product.Product_Price
     *
     * @mbg.generated Mon May 08 15:38:54 CST 2017
     */
    public void setProductPrice(BigDecimal productPrice) {
        this.productPrice = productPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.Product_PV
     *
     * @return the value of product.Product_PV
     *
     * @mbg.generated Mon May 08 15:38:54 CST 2017
     */
    public BigDecimal getProductPv() {
        return productPv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.Product_PV
     *
     * @param productPv the value for product.Product_PV
     *
     * @mbg.generated Mon May 08 15:38:54 CST 2017
     */
    public void setProductPv(BigDecimal productPv) {
        this.productPv = productPv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.Product_nvrUnit
     *
     * @return the value of product.Product_nvrUnit
     *
     * @mbg.generated Mon May 08 15:38:54 CST 2017
     */
    public String getProductNvrunit() {
        return productNvrunit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.Product_nvrUnit
     *
     * @param productNvrunit the value for product.Product_nvrUnit
     *
     * @mbg.generated Mon May 08 15:38:54 CST 2017
     */
    public void setProductNvrunit(String productNvrunit) {
        this.productNvrunit = productNvrunit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.Product_Format
     *
     * @return the value of product.Product_Format
     *
     * @mbg.generated Mon May 08 15:38:54 CST 2017
     */
    public String getProductFormat() {
        return productFormat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.Product_Format
     *
     * @param productFormat the value for product.Product_Format
     *
     * @mbg.generated Mon May 08 15:38:54 CST 2017
     */
    public void setProductFormat(String productFormat) {
        this.productFormat = productFormat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.Product_AddTime
     *
     * @return the value of product.Product_AddTime
     *
     * @mbg.generated Mon May 08 15:38:54 CST 2017
     */
    public Date getProductAddtime() {
        return productAddtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.Product_AddTime
     *
     * @param productAddtime the value for product.Product_AddTime
     *
     * @mbg.generated Mon May 08 15:38:54 CST 2017
     */
    public void setProductAddtime(Date productAddtime) {
        this.productAddtime = productAddtime;
    }
}