package com.my.test.springmvc.dao.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class UserExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user
     *
     * @mbg.generated Mon May 08 15:38:54 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user
     *
     * @mbg.generated Mon May 08 15:38:54 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user
     *
     * @mbg.generated Mon May 08 15:38:54 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Mon May 08 15:38:54 CST 2017
     */
    public UserExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Mon May 08 15:38:54 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Mon May 08 15:38:54 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Mon May 08 15:38:54 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Mon May 08 15:38:54 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Mon May 08 15:38:54 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Mon May 08 15:38:54 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Mon May 08 15:38:54 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Mon May 08 15:38:54 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Mon May 08 15:38:54 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Mon May 08 15:38:54 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table user
     *
     * @mbg.generated Mon May 08 15:38:54 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andUserUidIsNull() {
            addCriterion("user_UID is null");
            return (Criteria) this;
        }

        public Criteria andUserUidIsNotNull() {
            addCriterion("user_UID is not null");
            return (Criteria) this;
        }

        public Criteria andUserUidEqualTo(String value) {
            addCriterion("user_UID =", value, "userUid");
            return (Criteria) this;
        }

        public Criteria andUserUidNotEqualTo(String value) {
            addCriterion("user_UID <>", value, "userUid");
            return (Criteria) this;
        }

        public Criteria andUserUidGreaterThan(String value) {
            addCriterion("user_UID >", value, "userUid");
            return (Criteria) this;
        }

        public Criteria andUserUidGreaterThanOrEqualTo(String value) {
            addCriterion("user_UID >=", value, "userUid");
            return (Criteria) this;
        }

        public Criteria andUserUidLessThan(String value) {
            addCriterion("user_UID <", value, "userUid");
            return (Criteria) this;
        }

        public Criteria andUserUidLessThanOrEqualTo(String value) {
            addCriterion("user_UID <=", value, "userUid");
            return (Criteria) this;
        }

        public Criteria andUserUidLike(String value) {
            addCriterion("user_UID like", value, "userUid");
            return (Criteria) this;
        }

        public Criteria andUserUidNotLike(String value) {
            addCriterion("user_UID not like", value, "userUid");
            return (Criteria) this;
        }

        public Criteria andUserUidIn(List<String> values) {
            addCriterion("user_UID in", values, "userUid");
            return (Criteria) this;
        }

        public Criteria andUserUidNotIn(List<String> values) {
            addCriterion("user_UID not in", values, "userUid");
            return (Criteria) this;
        }

        public Criteria andUserUidBetween(String value1, String value2) {
            addCriterion("user_UID between", value1, value2, "userUid");
            return (Criteria) this;
        }

        public Criteria andUserUidNotBetween(String value1, String value2) {
            addCriterion("user_UID not between", value1, value2, "userUid");
            return (Criteria) this;
        }

        public Criteria andUserBranchIsNull() {
            addCriterion("user_Branch is null");
            return (Criteria) this;
        }

        public Criteria andUserBranchIsNotNull() {
            addCriterion("user_Branch is not null");
            return (Criteria) this;
        }

        public Criteria andUserBranchEqualTo(String value) {
            addCriterion("user_Branch =", value, "userBranch");
            return (Criteria) this;
        }

        public Criteria andUserBranchNotEqualTo(String value) {
            addCriterion("user_Branch <>", value, "userBranch");
            return (Criteria) this;
        }

        public Criteria andUserBranchGreaterThan(String value) {
            addCriterion("user_Branch >", value, "userBranch");
            return (Criteria) this;
        }

        public Criteria andUserBranchGreaterThanOrEqualTo(String value) {
            addCriterion("user_Branch >=", value, "userBranch");
            return (Criteria) this;
        }

        public Criteria andUserBranchLessThan(String value) {
            addCriterion("user_Branch <", value, "userBranch");
            return (Criteria) this;
        }

        public Criteria andUserBranchLessThanOrEqualTo(String value) {
            addCriterion("user_Branch <=", value, "userBranch");
            return (Criteria) this;
        }

        public Criteria andUserBranchLike(String value) {
            addCriterion("user_Branch like", value, "userBranch");
            return (Criteria) this;
        }

        public Criteria andUserBranchNotLike(String value) {
            addCriterion("user_Branch not like", value, "userBranch");
            return (Criteria) this;
        }

        public Criteria andUserBranchIn(List<String> values) {
            addCriterion("user_Branch in", values, "userBranch");
            return (Criteria) this;
        }

        public Criteria andUserBranchNotIn(List<String> values) {
            addCriterion("user_Branch not in", values, "userBranch");
            return (Criteria) this;
        }

        public Criteria andUserBranchBetween(String value1, String value2) {
            addCriterion("user_Branch between", value1, value2, "userBranch");
            return (Criteria) this;
        }

        public Criteria andUserBranchNotBetween(String value1, String value2) {
            addCriterion("user_Branch not between", value1, value2, "userBranch");
            return (Criteria) this;
        }

        public Criteria andUserUseridIsNull() {
            addCriterion("user_UserID is null");
            return (Criteria) this;
        }

        public Criteria andUserUseridIsNotNull() {
            addCriterion("user_UserID is not null");
            return (Criteria) this;
        }

        public Criteria andUserUseridEqualTo(String value) {
            addCriterion("user_UserID =", value, "userUserid");
            return (Criteria) this;
        }

        public Criteria andUserUseridNotEqualTo(String value) {
            addCriterion("user_UserID <>", value, "userUserid");
            return (Criteria) this;
        }

        public Criteria andUserUseridGreaterThan(String value) {
            addCriterion("user_UserID >", value, "userUserid");
            return (Criteria) this;
        }

        public Criteria andUserUseridGreaterThanOrEqualTo(String value) {
            addCriterion("user_UserID >=", value, "userUserid");
            return (Criteria) this;
        }

        public Criteria andUserUseridLessThan(String value) {
            addCriterion("user_UserID <", value, "userUserid");
            return (Criteria) this;
        }

        public Criteria andUserUseridLessThanOrEqualTo(String value) {
            addCriterion("user_UserID <=", value, "userUserid");
            return (Criteria) this;
        }

        public Criteria andUserUseridLike(String value) {
            addCriterion("user_UserID like", value, "userUserid");
            return (Criteria) this;
        }

        public Criteria andUserUseridNotLike(String value) {
            addCriterion("user_UserID not like", value, "userUserid");
            return (Criteria) this;
        }

        public Criteria andUserUseridIn(List<String> values) {
            addCriterion("user_UserID in", values, "userUserid");
            return (Criteria) this;
        }

        public Criteria andUserUseridNotIn(List<String> values) {
            addCriterion("user_UserID not in", values, "userUserid");
            return (Criteria) this;
        }

        public Criteria andUserUseridBetween(String value1, String value2) {
            addCriterion("user_UserID between", value1, value2, "userUserid");
            return (Criteria) this;
        }

        public Criteria andUserUseridNotBetween(String value1, String value2) {
            addCriterion("user_UserID not between", value1, value2, "userUserid");
            return (Criteria) this;
        }

        public Criteria andUserTeamnoIsNull() {
            addCriterion("user_TeamNO is null");
            return (Criteria) this;
        }

        public Criteria andUserTeamnoIsNotNull() {
            addCriterion("user_TeamNO is not null");
            return (Criteria) this;
        }

        public Criteria andUserTeamnoEqualTo(String value) {
            addCriterion("user_TeamNO =", value, "userTeamno");
            return (Criteria) this;
        }

        public Criteria andUserTeamnoNotEqualTo(String value) {
            addCriterion("user_TeamNO <>", value, "userTeamno");
            return (Criteria) this;
        }

        public Criteria andUserTeamnoGreaterThan(String value) {
            addCriterion("user_TeamNO >", value, "userTeamno");
            return (Criteria) this;
        }

        public Criteria andUserTeamnoGreaterThanOrEqualTo(String value) {
            addCriterion("user_TeamNO >=", value, "userTeamno");
            return (Criteria) this;
        }

        public Criteria andUserTeamnoLessThan(String value) {
            addCriterion("user_TeamNO <", value, "userTeamno");
            return (Criteria) this;
        }

        public Criteria andUserTeamnoLessThanOrEqualTo(String value) {
            addCriterion("user_TeamNO <=", value, "userTeamno");
            return (Criteria) this;
        }

        public Criteria andUserTeamnoLike(String value) {
            addCriterion("user_TeamNO like", value, "userTeamno");
            return (Criteria) this;
        }

        public Criteria andUserTeamnoNotLike(String value) {
            addCriterion("user_TeamNO not like", value, "userTeamno");
            return (Criteria) this;
        }

        public Criteria andUserTeamnoIn(List<String> values) {
            addCriterion("user_TeamNO in", values, "userTeamno");
            return (Criteria) this;
        }

        public Criteria andUserTeamnoNotIn(List<String> values) {
            addCriterion("user_TeamNO not in", values, "userTeamno");
            return (Criteria) this;
        }

        public Criteria andUserTeamnoBetween(String value1, String value2) {
            addCriterion("user_TeamNO between", value1, value2, "userTeamno");
            return (Criteria) this;
        }

        public Criteria andUserTeamnoNotBetween(String value1, String value2) {
            addCriterion("user_TeamNO not between", value1, value2, "userTeamno");
            return (Criteria) this;
        }

        public Criteria andUserUsernameIsNull() {
            addCriterion("user_UserName is null");
            return (Criteria) this;
        }

        public Criteria andUserUsernameIsNotNull() {
            addCriterion("user_UserName is not null");
            return (Criteria) this;
        }

        public Criteria andUserUsernameEqualTo(String value) {
            addCriterion("user_UserName =", value, "userUsername");
            return (Criteria) this;
        }

        public Criteria andUserUsernameNotEqualTo(String value) {
            addCriterion("user_UserName <>", value, "userUsername");
            return (Criteria) this;
        }

        public Criteria andUserUsernameGreaterThan(String value) {
            addCriterion("user_UserName >", value, "userUsername");
            return (Criteria) this;
        }

        public Criteria andUserUsernameGreaterThanOrEqualTo(String value) {
            addCriterion("user_UserName >=", value, "userUsername");
            return (Criteria) this;
        }

        public Criteria andUserUsernameLessThan(String value) {
            addCriterion("user_UserName <", value, "userUsername");
            return (Criteria) this;
        }

        public Criteria andUserUsernameLessThanOrEqualTo(String value) {
            addCriterion("user_UserName <=", value, "userUsername");
            return (Criteria) this;
        }

        public Criteria andUserUsernameLike(String value) {
            addCriterion("user_UserName like", value, "userUsername");
            return (Criteria) this;
        }

        public Criteria andUserUsernameNotLike(String value) {
            addCriterion("user_UserName not like", value, "userUsername");
            return (Criteria) this;
        }

        public Criteria andUserUsernameIn(List<String> values) {
            addCriterion("user_UserName in", values, "userUsername");
            return (Criteria) this;
        }

        public Criteria andUserUsernameNotIn(List<String> values) {
            addCriterion("user_UserName not in", values, "userUsername");
            return (Criteria) this;
        }

        public Criteria andUserUsernameBetween(String value1, String value2) {
            addCriterion("user_UserName between", value1, value2, "userUsername");
            return (Criteria) this;
        }

        public Criteria andUserUsernameNotBetween(String value1, String value2) {
            addCriterion("user_UserName not between", value1, value2, "userUsername");
            return (Criteria) this;
        }

        public Criteria andUserAddtimeIsNull() {
            addCriterion("user_AddTime is null");
            return (Criteria) this;
        }

        public Criteria andUserAddtimeIsNotNull() {
            addCriterion("user_AddTime is not null");
            return (Criteria) this;
        }

        public Criteria andUserAddtimeEqualTo(Date value) {
            addCriterion("user_AddTime =", value, "userAddtime");
            return (Criteria) this;
        }

        public Criteria andUserAddtimeNotEqualTo(Date value) {
            addCriterion("user_AddTime <>", value, "userAddtime");
            return (Criteria) this;
        }

        public Criteria andUserAddtimeGreaterThan(Date value) {
            addCriterion("user_AddTime >", value, "userAddtime");
            return (Criteria) this;
        }

        public Criteria andUserAddtimeGreaterThanOrEqualTo(Date value) {
            addCriterion("user_AddTime >=", value, "userAddtime");
            return (Criteria) this;
        }

        public Criteria andUserAddtimeLessThan(Date value) {
            addCriterion("user_AddTime <", value, "userAddtime");
            return (Criteria) this;
        }

        public Criteria andUserAddtimeLessThanOrEqualTo(Date value) {
            addCriterion("user_AddTime <=", value, "userAddtime");
            return (Criteria) this;
        }

        public Criteria andUserAddtimeIn(List<Date> values) {
            addCriterion("user_AddTime in", values, "userAddtime");
            return (Criteria) this;
        }

        public Criteria andUserAddtimeNotIn(List<Date> values) {
            addCriterion("user_AddTime not in", values, "userAddtime");
            return (Criteria) this;
        }

        public Criteria andUserAddtimeBetween(Date value1, Date value2) {
            addCriterion("user_AddTime between", value1, value2, "userAddtime");
            return (Criteria) this;
        }

        public Criteria andUserAddtimeNotBetween(Date value1, Date value2) {
            addCriterion("user_AddTime not between", value1, value2, "userAddtime");
            return (Criteria) this;
        }

        public Criteria andUserOfficialtimeIsNull() {
            addCriterion("user_OfficialTime is null");
            return (Criteria) this;
        }

        public Criteria andUserOfficialtimeIsNotNull() {
            addCriterion("user_OfficialTime is not null");
            return (Criteria) this;
        }

        public Criteria andUserOfficialtimeEqualTo(Date value) {
            addCriterion("user_OfficialTime =", value, "userOfficialtime");
            return (Criteria) this;
        }

        public Criteria andUserOfficialtimeNotEqualTo(Date value) {
            addCriterion("user_OfficialTime <>", value, "userOfficialtime");
            return (Criteria) this;
        }

        public Criteria andUserOfficialtimeGreaterThan(Date value) {
            addCriterion("user_OfficialTime >", value, "userOfficialtime");
            return (Criteria) this;
        }

        public Criteria andUserOfficialtimeGreaterThanOrEqualTo(Date value) {
            addCriterion("user_OfficialTime >=", value, "userOfficialtime");
            return (Criteria) this;
        }

        public Criteria andUserOfficialtimeLessThan(Date value) {
            addCriterion("user_OfficialTime <", value, "userOfficialtime");
            return (Criteria) this;
        }

        public Criteria andUserOfficialtimeLessThanOrEqualTo(Date value) {
            addCriterion("user_OfficialTime <=", value, "userOfficialtime");
            return (Criteria) this;
        }

        public Criteria andUserOfficialtimeIn(List<Date> values) {
            addCriterion("user_OfficialTime in", values, "userOfficialtime");
            return (Criteria) this;
        }

        public Criteria andUserOfficialtimeNotIn(List<Date> values) {
            addCriterion("user_OfficialTime not in", values, "userOfficialtime");
            return (Criteria) this;
        }

        public Criteria andUserOfficialtimeBetween(Date value1, Date value2) {
            addCriterion("user_OfficialTime between", value1, value2, "userOfficialtime");
            return (Criteria) this;
        }

        public Criteria andUserOfficialtimeNotBetween(Date value1, Date value2) {
            addCriterion("user_OfficialTime not between", value1, value2, "userOfficialtime");
            return (Criteria) this;
        }

        public Criteria andUserIsfromebIsNull() {
            addCriterion("user_IsFromEB is null");
            return (Criteria) this;
        }

        public Criteria andUserIsfromebIsNotNull() {
            addCriterion("user_IsFromEB is not null");
            return (Criteria) this;
        }

        public Criteria andUserIsfromebEqualTo(String value) {
            addCriterion("user_IsFromEB =", value, "userIsfromeb");
            return (Criteria) this;
        }

        public Criteria andUserIsfromebNotEqualTo(String value) {
            addCriterion("user_IsFromEB <>", value, "userIsfromeb");
            return (Criteria) this;
        }

        public Criteria andUserIsfromebGreaterThan(String value) {
            addCriterion("user_IsFromEB >", value, "userIsfromeb");
            return (Criteria) this;
        }

        public Criteria andUserIsfromebGreaterThanOrEqualTo(String value) {
            addCriterion("user_IsFromEB >=", value, "userIsfromeb");
            return (Criteria) this;
        }

        public Criteria andUserIsfromebLessThan(String value) {
            addCriterion("user_IsFromEB <", value, "userIsfromeb");
            return (Criteria) this;
        }

        public Criteria andUserIsfromebLessThanOrEqualTo(String value) {
            addCriterion("user_IsFromEB <=", value, "userIsfromeb");
            return (Criteria) this;
        }

        public Criteria andUserIsfromebLike(String value) {
            addCriterion("user_IsFromEB like", value, "userIsfromeb");
            return (Criteria) this;
        }

        public Criteria andUserIsfromebNotLike(String value) {
            addCriterion("user_IsFromEB not like", value, "userIsfromeb");
            return (Criteria) this;
        }

        public Criteria andUserIsfromebIn(List<String> values) {
            addCriterion("user_IsFromEB in", values, "userIsfromeb");
            return (Criteria) this;
        }

        public Criteria andUserIsfromebNotIn(List<String> values) {
            addCriterion("user_IsFromEB not in", values, "userIsfromeb");
            return (Criteria) this;
        }

        public Criteria andUserIsfromebBetween(String value1, String value2) {
            addCriterion("user_IsFromEB between", value1, value2, "userIsfromeb");
            return (Criteria) this;
        }

        public Criteria andUserIsfromebNotBetween(String value1, String value2) {
            addCriterion("user_IsFromEB not between", value1, value2, "userIsfromeb");
            return (Criteria) this;
        }

        public Criteria andUserIsdirectIsNull() {
            addCriterion("user_IsDirect is null");
            return (Criteria) this;
        }

        public Criteria andUserIsdirectIsNotNull() {
            addCriterion("user_IsDirect is not null");
            return (Criteria) this;
        }

        public Criteria andUserIsdirectEqualTo(String value) {
            addCriterion("user_IsDirect =", value, "userIsdirect");
            return (Criteria) this;
        }

        public Criteria andUserIsdirectNotEqualTo(String value) {
            addCriterion("user_IsDirect <>", value, "userIsdirect");
            return (Criteria) this;
        }

        public Criteria andUserIsdirectGreaterThan(String value) {
            addCriterion("user_IsDirect >", value, "userIsdirect");
            return (Criteria) this;
        }

        public Criteria andUserIsdirectGreaterThanOrEqualTo(String value) {
            addCriterion("user_IsDirect >=", value, "userIsdirect");
            return (Criteria) this;
        }

        public Criteria andUserIsdirectLessThan(String value) {
            addCriterion("user_IsDirect <", value, "userIsdirect");
            return (Criteria) this;
        }

        public Criteria andUserIsdirectLessThanOrEqualTo(String value) {
            addCriterion("user_IsDirect <=", value, "userIsdirect");
            return (Criteria) this;
        }

        public Criteria andUserIsdirectLike(String value) {
            addCriterion("user_IsDirect like", value, "userIsdirect");
            return (Criteria) this;
        }

        public Criteria andUserIsdirectNotLike(String value) {
            addCriterion("user_IsDirect not like", value, "userIsdirect");
            return (Criteria) this;
        }

        public Criteria andUserIsdirectIn(List<String> values) {
            addCriterion("user_IsDirect in", values, "userIsdirect");
            return (Criteria) this;
        }

        public Criteria andUserIsdirectNotIn(List<String> values) {
            addCriterion("user_IsDirect not in", values, "userIsdirect");
            return (Criteria) this;
        }

        public Criteria andUserIsdirectBetween(String value1, String value2) {
            addCriterion("user_IsDirect between", value1, value2, "userIsdirect");
            return (Criteria) this;
        }

        public Criteria andUserIsdirectNotBetween(String value1, String value2) {
            addCriterion("user_IsDirect not between", value1, value2, "userIsdirect");
            return (Criteria) this;
        }

        public Criteria andUserLoginpwdIsNull() {
            addCriterion("user_LoginPWD is null");
            return (Criteria) this;
        }

        public Criteria andUserLoginpwdIsNotNull() {
            addCriterion("user_LoginPWD is not null");
            return (Criteria) this;
        }

        public Criteria andUserLoginpwdEqualTo(String value) {
            addCriterion("user_LoginPWD =", value, "userLoginpwd");
            return (Criteria) this;
        }

        public Criteria andUserLoginpwdNotEqualTo(String value) {
            addCriterion("user_LoginPWD <>", value, "userLoginpwd");
            return (Criteria) this;
        }

        public Criteria andUserLoginpwdGreaterThan(String value) {
            addCriterion("user_LoginPWD >", value, "userLoginpwd");
            return (Criteria) this;
        }

        public Criteria andUserLoginpwdGreaterThanOrEqualTo(String value) {
            addCriterion("user_LoginPWD >=", value, "userLoginpwd");
            return (Criteria) this;
        }

        public Criteria andUserLoginpwdLessThan(String value) {
            addCriterion("user_LoginPWD <", value, "userLoginpwd");
            return (Criteria) this;
        }

        public Criteria andUserLoginpwdLessThanOrEqualTo(String value) {
            addCriterion("user_LoginPWD <=", value, "userLoginpwd");
            return (Criteria) this;
        }

        public Criteria andUserLoginpwdLike(String value) {
            addCriterion("user_LoginPWD like", value, "userLoginpwd");
            return (Criteria) this;
        }

        public Criteria andUserLoginpwdNotLike(String value) {
            addCriterion("user_LoginPWD not like", value, "userLoginpwd");
            return (Criteria) this;
        }

        public Criteria andUserLoginpwdIn(List<String> values) {
            addCriterion("user_LoginPWD in", values, "userLoginpwd");
            return (Criteria) this;
        }

        public Criteria andUserLoginpwdNotIn(List<String> values) {
            addCriterion("user_LoginPWD not in", values, "userLoginpwd");
            return (Criteria) this;
        }

        public Criteria andUserLoginpwdBetween(String value1, String value2) {
            addCriterion("user_LoginPWD between", value1, value2, "userLoginpwd");
            return (Criteria) this;
        }

        public Criteria andUserLoginpwdNotBetween(String value1, String value2) {
            addCriterion("user_LoginPWD not between", value1, value2, "userLoginpwd");
            return (Criteria) this;
        }

        public Criteria andUserOperatpwdIsNull() {
            addCriterion("user_OperatPWD is null");
            return (Criteria) this;
        }

        public Criteria andUserOperatpwdIsNotNull() {
            addCriterion("user_OperatPWD is not null");
            return (Criteria) this;
        }

        public Criteria andUserOperatpwdEqualTo(String value) {
            addCriterion("user_OperatPWD =", value, "userOperatpwd");
            return (Criteria) this;
        }

        public Criteria andUserOperatpwdNotEqualTo(String value) {
            addCriterion("user_OperatPWD <>", value, "userOperatpwd");
            return (Criteria) this;
        }

        public Criteria andUserOperatpwdGreaterThan(String value) {
            addCriterion("user_OperatPWD >", value, "userOperatpwd");
            return (Criteria) this;
        }

        public Criteria andUserOperatpwdGreaterThanOrEqualTo(String value) {
            addCriterion("user_OperatPWD >=", value, "userOperatpwd");
            return (Criteria) this;
        }

        public Criteria andUserOperatpwdLessThan(String value) {
            addCriterion("user_OperatPWD <", value, "userOperatpwd");
            return (Criteria) this;
        }

        public Criteria andUserOperatpwdLessThanOrEqualTo(String value) {
            addCriterion("user_OperatPWD <=", value, "userOperatpwd");
            return (Criteria) this;
        }

        public Criteria andUserOperatpwdLike(String value) {
            addCriterion("user_OperatPWD like", value, "userOperatpwd");
            return (Criteria) this;
        }

        public Criteria andUserOperatpwdNotLike(String value) {
            addCriterion("user_OperatPWD not like", value, "userOperatpwd");
            return (Criteria) this;
        }

        public Criteria andUserOperatpwdIn(List<String> values) {
            addCriterion("user_OperatPWD in", values, "userOperatpwd");
            return (Criteria) this;
        }

        public Criteria andUserOperatpwdNotIn(List<String> values) {
            addCriterion("user_OperatPWD not in", values, "userOperatpwd");
            return (Criteria) this;
        }

        public Criteria andUserOperatpwdBetween(String value1, String value2) {
            addCriterion("user_OperatPWD between", value1, value2, "userOperatpwd");
            return (Criteria) this;
        }

        public Criteria andUserOperatpwdNotBetween(String value1, String value2) {
            addCriterion("user_OperatPWD not between", value1, value2, "userOperatpwd");
            return (Criteria) this;
        }

        public Criteria andUserWrongpwdtimesIsNull() {
            addCriterion("user_WrongPwdTimes is null");
            return (Criteria) this;
        }

        public Criteria andUserWrongpwdtimesIsNotNull() {
            addCriterion("user_WrongPwdTimes is not null");
            return (Criteria) this;
        }

        public Criteria andUserWrongpwdtimesEqualTo(Boolean value) {
            addCriterion("user_WrongPwdTimes =", value, "userWrongpwdtimes");
            return (Criteria) this;
        }

        public Criteria andUserWrongpwdtimesNotEqualTo(Boolean value) {
            addCriterion("user_WrongPwdTimes <>", value, "userWrongpwdtimes");
            return (Criteria) this;
        }

        public Criteria andUserWrongpwdtimesGreaterThan(Boolean value) {
            addCriterion("user_WrongPwdTimes >", value, "userWrongpwdtimes");
            return (Criteria) this;
        }

        public Criteria andUserWrongpwdtimesGreaterThanOrEqualTo(Boolean value) {
            addCriterion("user_WrongPwdTimes >=", value, "userWrongpwdtimes");
            return (Criteria) this;
        }

        public Criteria andUserWrongpwdtimesLessThan(Boolean value) {
            addCriterion("user_WrongPwdTimes <", value, "userWrongpwdtimes");
            return (Criteria) this;
        }

        public Criteria andUserWrongpwdtimesLessThanOrEqualTo(Boolean value) {
            addCriterion("user_WrongPwdTimes <=", value, "userWrongpwdtimes");
            return (Criteria) this;
        }

        public Criteria andUserWrongpwdtimesIn(List<Boolean> values) {
            addCriterion("user_WrongPwdTimes in", values, "userWrongpwdtimes");
            return (Criteria) this;
        }

        public Criteria andUserWrongpwdtimesNotIn(List<Boolean> values) {
            addCriterion("user_WrongPwdTimes not in", values, "userWrongpwdtimes");
            return (Criteria) this;
        }

        public Criteria andUserWrongpwdtimesBetween(Boolean value1, Boolean value2) {
            addCriterion("user_WrongPwdTimes between", value1, value2, "userWrongpwdtimes");
            return (Criteria) this;
        }

        public Criteria andUserWrongpwdtimesNotBetween(Boolean value1, Boolean value2) {
            addCriterion("user_WrongPwdTimes not between", value1, value2, "userWrongpwdtimes");
            return (Criteria) this;
        }

        public Criteria andUserLastedittimeIsNull() {
            addCriterion("user_LastEditTime is null");
            return (Criteria) this;
        }

        public Criteria andUserLastedittimeIsNotNull() {
            addCriterion("user_LastEditTime is not null");
            return (Criteria) this;
        }

        public Criteria andUserLastedittimeEqualTo(Date value) {
            addCriterion("user_LastEditTime =", value, "userLastedittime");
            return (Criteria) this;
        }

        public Criteria andUserLastedittimeNotEqualTo(Date value) {
            addCriterion("user_LastEditTime <>", value, "userLastedittime");
            return (Criteria) this;
        }

        public Criteria andUserLastedittimeGreaterThan(Date value) {
            addCriterion("user_LastEditTime >", value, "userLastedittime");
            return (Criteria) this;
        }

        public Criteria andUserLastedittimeGreaterThanOrEqualTo(Date value) {
            addCriterion("user_LastEditTime >=", value, "userLastedittime");
            return (Criteria) this;
        }

        public Criteria andUserLastedittimeLessThan(Date value) {
            addCriterion("user_LastEditTime <", value, "userLastedittime");
            return (Criteria) this;
        }

        public Criteria andUserLastedittimeLessThanOrEqualTo(Date value) {
            addCriterion("user_LastEditTime <=", value, "userLastedittime");
            return (Criteria) this;
        }

        public Criteria andUserLastedittimeIn(List<Date> values) {
            addCriterion("user_LastEditTime in", values, "userLastedittime");
            return (Criteria) this;
        }

        public Criteria andUserLastedittimeNotIn(List<Date> values) {
            addCriterion("user_LastEditTime not in", values, "userLastedittime");
            return (Criteria) this;
        }

        public Criteria andUserLastedittimeBetween(Date value1, Date value2) {
            addCriterion("user_LastEditTime between", value1, value2, "userLastedittime");
            return (Criteria) this;
        }

        public Criteria andUserLastedittimeNotBetween(Date value1, Date value2) {
            addCriterion("user_LastEditTime not between", value1, value2, "userLastedittime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table user
     *
     * @mbg.generated do_not_delete_during_merge Mon May 08 15:38:54 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table user
     *
     * @mbg.generated Mon May 08 15:38:54 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}