package com.my.test.springmvc.dao.model;

import java.util.Date;

public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_UID
     *
     * @mbg.generated Mon May 08 15:38:54 CST 2017
     */
    private String userUid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_Branch
     *
     * @mbg.generated Mon May 08 15:38:54 CST 2017
     */
    private String userBranch;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_UserID
     *
     * @mbg.generated Mon May 08 15:38:54 CST 2017
     */
    private String userUserid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_TeamNO
     *
     * @mbg.generated Mon May 08 15:38:54 CST 2017
     */
    private String userTeamno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_UserName
     *
     * @mbg.generated Mon May 08 15:38:54 CST 2017
     */
    private String userUsername;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_AddTime
     *
     * @mbg.generated Mon May 08 15:38:54 CST 2017
     */
    private Date userAddtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_OfficialTime
     *
     * @mbg.generated Mon May 08 15:38:54 CST 2017
     */
    private Date userOfficialtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_IsFromEB
     *
     * @mbg.generated Mon May 08 15:38:54 CST 2017
     */
    private String userIsfromeb;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_IsDirect
     *
     * @mbg.generated Mon May 08 15:38:54 CST 2017
     */
    private String userIsdirect;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_LoginPWD
     *
     * @mbg.generated Mon May 08 15:38:54 CST 2017
     */
    private String userLoginpwd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_OperatPWD
     *
     * @mbg.generated Mon May 08 15:38:54 CST 2017
     */
    private String userOperatpwd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_WrongPwdTimes
     *
     * @mbg.generated Mon May 08 15:38:54 CST 2017
     */
    private Boolean userWrongpwdtimes;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_LastEditTime
     *
     * @mbg.generated Mon May 08 15:38:54 CST 2017
     */
    private Date userLastedittime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_UID
     *
     * @return the value of user.user_UID
     *
     * @mbg.generated Mon May 08 15:38:54 CST 2017
     */
    public String getUserUid() {
        return userUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_UID
     *
     * @param userUid the value for user.user_UID
     *
     * @mbg.generated Mon May 08 15:38:54 CST 2017
     */
    public void setUserUid(String userUid) {
        this.userUid = userUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_Branch
     *
     * @return the value of user.user_Branch
     *
     * @mbg.generated Mon May 08 15:38:54 CST 2017
     */
    public String getUserBranch() {
        return userBranch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_Branch
     *
     * @param userBranch the value for user.user_Branch
     *
     * @mbg.generated Mon May 08 15:38:54 CST 2017
     */
    public void setUserBranch(String userBranch) {
        this.userBranch = userBranch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_UserID
     *
     * @return the value of user.user_UserID
     *
     * @mbg.generated Mon May 08 15:38:54 CST 2017
     */
    public String getUserUserid() {
        return userUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_UserID
     *
     * @param userUserid the value for user.user_UserID
     *
     * @mbg.generated Mon May 08 15:38:54 CST 2017
     */
    public void setUserUserid(String userUserid) {
        this.userUserid = userUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_TeamNO
     *
     * @return the value of user.user_TeamNO
     *
     * @mbg.generated Mon May 08 15:38:54 CST 2017
     */
    public String getUserTeamno() {
        return userTeamno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_TeamNO
     *
     * @param userTeamno the value for user.user_TeamNO
     *
     * @mbg.generated Mon May 08 15:38:54 CST 2017
     */
    public void setUserTeamno(String userTeamno) {
        this.userTeamno = userTeamno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_UserName
     *
     * @return the value of user.user_UserName
     *
     * @mbg.generated Mon May 08 15:38:54 CST 2017
     */
    public String getUserUsername() {
        return userUsername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_UserName
     *
     * @param userUsername the value for user.user_UserName
     *
     * @mbg.generated Mon May 08 15:38:54 CST 2017
     */
    public void setUserUsername(String userUsername) {
        this.userUsername = userUsername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_AddTime
     *
     * @return the value of user.user_AddTime
     *
     * @mbg.generated Mon May 08 15:38:54 CST 2017
     */
    public Date getUserAddtime() {
        return userAddtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_AddTime
     *
     * @param userAddtime the value for user.user_AddTime
     *
     * @mbg.generated Mon May 08 15:38:54 CST 2017
     */
    public void setUserAddtime(Date userAddtime) {
        this.userAddtime = userAddtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_OfficialTime
     *
     * @return the value of user.user_OfficialTime
     *
     * @mbg.generated Mon May 08 15:38:54 CST 2017
     */
    public Date getUserOfficialtime() {
        return userOfficialtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_OfficialTime
     *
     * @param userOfficialtime the value for user.user_OfficialTime
     *
     * @mbg.generated Mon May 08 15:38:54 CST 2017
     */
    public void setUserOfficialtime(Date userOfficialtime) {
        this.userOfficialtime = userOfficialtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_IsFromEB
     *
     * @return the value of user.user_IsFromEB
     *
     * @mbg.generated Mon May 08 15:38:54 CST 2017
     */
    public String getUserIsfromeb() {
        return userIsfromeb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_IsFromEB
     *
     * @param userIsfromeb the value for user.user_IsFromEB
     *
     * @mbg.generated Mon May 08 15:38:54 CST 2017
     */
    public void setUserIsfromeb(String userIsfromeb) {
        this.userIsfromeb = userIsfromeb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_IsDirect
     *
     * @return the value of user.user_IsDirect
     *
     * @mbg.generated Mon May 08 15:38:54 CST 2017
     */
    public String getUserIsdirect() {
        return userIsdirect;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_IsDirect
     *
     * @param userIsdirect the value for user.user_IsDirect
     *
     * @mbg.generated Mon May 08 15:38:54 CST 2017
     */
    public void setUserIsdirect(String userIsdirect) {
        this.userIsdirect = userIsdirect;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_LoginPWD
     *
     * @return the value of user.user_LoginPWD
     *
     * @mbg.generated Mon May 08 15:38:54 CST 2017
     */
    public String getUserLoginpwd() {
        return userLoginpwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_LoginPWD
     *
     * @param userLoginpwd the value for user.user_LoginPWD
     *
     * @mbg.generated Mon May 08 15:38:54 CST 2017
     */
    public void setUserLoginpwd(String userLoginpwd) {
        this.userLoginpwd = userLoginpwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_OperatPWD
     *
     * @return the value of user.user_OperatPWD
     *
     * @mbg.generated Mon May 08 15:38:54 CST 2017
     */
    public String getUserOperatpwd() {
        return userOperatpwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_OperatPWD
     *
     * @param userOperatpwd the value for user.user_OperatPWD
     *
     * @mbg.generated Mon May 08 15:38:54 CST 2017
     */
    public void setUserOperatpwd(String userOperatpwd) {
        this.userOperatpwd = userOperatpwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_WrongPwdTimes
     *
     * @return the value of user.user_WrongPwdTimes
     *
     * @mbg.generated Mon May 08 15:38:54 CST 2017
     */
    public Boolean getUserWrongpwdtimes() {
        return userWrongpwdtimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_WrongPwdTimes
     *
     * @param userWrongpwdtimes the value for user.user_WrongPwdTimes
     *
     * @mbg.generated Mon May 08 15:38:54 CST 2017
     */
    public void setUserWrongpwdtimes(Boolean userWrongpwdtimes) {
        this.userWrongpwdtimes = userWrongpwdtimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_LastEditTime
     *
     * @return the value of user.user_LastEditTime
     *
     * @mbg.generated Mon May 08 15:38:54 CST 2017
     */
    public Date getUserLastedittime() {
        return userLastedittime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_LastEditTime
     *
     * @param userLastedittime the value for user.user_LastEditTime
     *
     * @mbg.generated Mon May 08 15:38:54 CST 2017
     */
    public void setUserLastedittime(Date userLastedittime) {
        this.userLastedittime = userLastedittime;
    }
}